# Generated by Django 4.2.2 on 2023-06-08 07:19

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[720, 400], upload_to='instagram', verbose_name='Image')),
                ('link', models.URLField(verbose_name='Link')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('created_day', models.DateField(blank=True, null=True, verbose_name='Created day')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Instagram post',
                'verbose_name_plural': 'Instagram posts',
            },
        ),
        migrations.CreateModel(
            name='InstagramScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('target_username', models.CharField(max_length=255, verbose_name='Target username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Instagram scrape',
                'verbose_name_plural': 'Instagram scrapes',
            },
        ),
    ]
